on: push
name: Bundle and Publish Sources
jobs:
    build:
        name: Bundle and Publish Sources
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Extract branch name
              id: extract_branch
              shell: bash
              run: |
                  echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

            - run: npm install

            - run: npm run bundle -- --folder=${{ steps.extract_branch.outputs.branch }}

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: bundles
